### ISSUE TITLE
Advanced Android in Kotlin: Custom Views 2.1 [Step #8][typo]

### ISSUE THREAD

**Issue by jrbasil** [googlecodelabs/android-kotlin-drawing-custom-views#42]
**Describe the problem**
Typo

**In which lesson and step of the codelab can this issue be found?**
Custom Views 2.1, Step 8

**How to reproduce?**
![image](https://user-images.githubusercontent.com/9315733/156868988-d0d1c2f3-1388-40ed-96ef-b4f45d3d7bb6.png)

**Additional information**
Unrelated:  Not a bug, but in Step 9, you could save an import by replacing AccessibilityNodeInfo with AccessibilityNodeInfoCompat
![image](https://user-images.githubusercontent.com/9315733/156869085-4e9ea01c-7fcd-479c-8b51-32f6e3f04e6f.png)

**codelab:** advanced-android-kotlin

**Comment by bxcd** [comment]
Already reported
